from PyQt5 import QtCore, QtGui, QtWidgets


class OpenFileDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(689, 406)
        self.fileLabel = QtWidgets.QLabel(Dialog)
        self.fileLabel.setGeometry(QtCore.QRect(20, 30, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.fileLabel.setFont(font)
        self.fileLabel.setObjectName("fileLabel")
        self.separatorBox = QtWidgets.QGroupBox(Dialog)
        self.separatorBox.setGeometry(QtCore.QRect(40, 70, 251, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.separatorBox.setFont(font)
        self.separatorBox.setObjectName("separatorBox")
        self.tabRadio = QtWidgets.QRadioButton(self.separatorBox)
        self.tabRadio.setGeometry(QtCore.QRect(10, 20, 82, 31))
        self.tabRadio.setObjectName("tabRadio")
        self.spaceRadio = QtWidgets.QRadioButton(self.separatorBox)
        self.spaceRadio.setGeometry(QtCore.QRect(10, 50, 82, 21))
        self.spaceRadio.setObjectName("spaceRadio")
        self.commaRadio = QtWidgets.QRadioButton(self.separatorBox)
        self.commaRadio.setGeometry(QtCore.QRect(10, 80, 121, 17))
        self.commaRadio.setObjectName("commaRadio")
        self.semicolonRadio = QtWidgets.QRadioButton(self.separatorBox)
        self.semicolonRadio.setGeometry(QtCore.QRect(10, 110, 131, 17))
        self.semicolonRadio.setObjectName("semicolonRadio")
        self.checkBoxHeaders = QtWidgets.QCheckBox(Dialog)
        self.checkBoxHeaders.setGeometry(QtCore.QRect(40, 240, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.checkBoxHeaders.setFont(font)
        self.checkBoxHeaders.setObjectName("checkBoxHeaders")
        self.okButton = QtWidgets.QPushButton(Dialog)
        self.okButton.setGeometry(QtCore.QRect(470, 350, 75, 23))
        self.okButton.setObjectName("okButton")
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setGeometry(QtCore.QRect(560, 350, 75, 23))
        self.cancelButton.setObjectName("cancelButton")
        self.filePathInput = QtWidgets.QLineEdit(Dialog)
        self.filePathInput.setGeometry(QtCore.QRect(50, 20, 621, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.filePathInput.setFont(font)
        self.filePathInput.setObjectName("filePathInput")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Otwórz plik"))
        self.fileLabel.setText(_translate("Dialog", "Plik"))
        self.separatorBox.setTitle(_translate("Dialog", "Separator"))
        self.tabRadio.setText(_translate("Dialog", "Tab"))
        self.spaceRadio.setText(_translate("Dialog", "Spacja"))
        self.commaRadio.setText(_translate("Dialog", "Przecinek"))
        self.semicolonRadio.setText(_translate("Dialog", "Średnik"))
        self.checkBoxHeaders.setText(_translate("Dialog", "Nazwy kolumn"))
        self.okButton.setText(_translate("Dialog", "OK"))
        self.cancelButton.setText(_translate("Dialog", "Anuluj"))

