from PyQt5 import QtCore, QtGui, QtWidgets


class Plot2DDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(329, 439)
        self.comboBoxColumnX = QtWidgets.QComboBox(Dialog)
        self.comboBoxColumnX.setGeometry(QtCore.QRect(80, 10, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBoxColumnX.setFont(font)
        self.comboBoxColumnX.setObjectName("comboBoxColumnX")
        self.comboBoxColumnY = QtWidgets.QComboBox(Dialog)
        self.comboBoxColumnY.setGeometry(QtCore.QRect(80, 80, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBoxColumnY.setFont(font)
        self.comboBoxColumnY.setObjectName("comboBoxColumnY")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 20, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 90, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.okButton = QtWidgets.QPushButton(Dialog)
        self.okButton.setGeometry(QtCore.QRect(180, 380, 71, 31))
        self.okButton.setObjectName("okButton")
        self.checkBoxColors = QtWidgets.QCheckBox(Dialog)
        self.checkBoxColors.setGeometry(QtCore.QRect(80, 150, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBoxColors.setFont(font)
        self.checkBoxColors.setObjectName("checkBoxColors")
        self.comboBoxClass = QtWidgets.QComboBox(Dialog)
        self.comboBoxClass.setGeometry(QtCore.QRect(90, 200, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBoxClass.setFont(font)
        self.comboBoxClass.setObjectName("comboBoxClass")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 210, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "X"))
        self.label_2.setText(_translate("Dialog", "Y"))
        self.okButton.setText(_translate("Dialog", "OK"))
        self.checkBoxColors.setText(_translate("Dialog", "Zastosuj kolory do klas"))
        self.label_3.setText(_translate("Dialog", "Klasa"))
