from PyQt5 import QtCore, QtGui, QtWidgets


class SubsetDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(870, 676)
        self.comboBoxColumn = QtWidgets.QComboBox(Dialog)
        self.comboBoxColumn.setGeometry(QtCore.QRect(130, 20, 291, 41))
        self.comboBoxColumn.setObjectName("comboBoxColumn")
        self.linePercent = QtWidgets.QLineEdit(Dialog)
        self.linePercent.setGeometry(QtCore.QRect(100, 100, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.linePercent.setFont(font)
        self.linePercent.setObjectName("linePercent")
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setGeometry(QtCore.QRect(600, 110, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 100, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.columnLabel = QtWidgets.QLabel(Dialog)
        self.columnLabel.setGeometry(QtCore.QRect(30, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.columnLabel.setFont(font)
        self.columnLabel.setObjectName("columnLabel")
        self.okButton = QtWidgets.QPushButton(Dialog)
        self.okButton.setGeometry(QtCore.QRect(480, 110, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.okButton.setFont(font)
        self.okButton.setObjectName("okButton")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(200, 70, 261, 101))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.radioButtonMax = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonMax.setGeometry(QtCore.QRect(20, 30, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButtonMax.setFont(font)
        self.radioButtonMax.setObjectName("radioButtonMax")
        self.radioButtonMin = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonMin.setGeometry(QtCore.QRect(20, 70, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButtonMin.setFont(font)
        self.radioButtonMin.setObjectName("radioButtonMin")
        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setGeometry(QtCore.QRect(10, 180, 841, 481))
        self.tableView.setObjectName("tableView")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.cancelButton.setText(_translate("Dialog", "Anuluj"))
        self.label.setText(_translate("Dialog", "Procent"))
        self.columnLabel.setText(_translate("Dialog", "Kolumna"))
        self.okButton.setText(_translate("Dialog", "OK"))
        self.radioButtonMax.setText(_translate("Dialog", "Największych wartości"))
        self.radioButtonMin.setText(_translate("Dialog", "Najmniejszych wartości"))

