from PyQt5 import QtCore, QtGui, QtWidgets


class Vectorize_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(870, 676)
        self.drawButton = QtWidgets.QPushButton(Dialog)
        self.drawButton.setGeometry(QtCore.QRect(740, 120, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.drawButton.setFont(font)
        self.drawButton.setObjectName("drawButton")
        self.addButton = QtWidgets.QPushButton(Dialog)
        self.addButton.setGeometry(QtCore.QRect(20, 110, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.addButton.setFont(font)
        self.addButton.setObjectName("addButton")
        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setGeometry(QtCore.QRect(10, 180, 841, 481))
        self.tableView.setObjectName("tableView")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 721, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.newValues = QtWidgets.QLineEdit(Dialog)
        self.newValues.setGeometry(QtCore.QRect(20, 60, 691, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.newValues.setFont(font)
        self.newValues.setObjectName("newValues")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(200, 120, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.newObject_label = QtWidgets.QLabel(Dialog)
        self.newObject_label.setGeometry(QtCore.QRect(300, 120, 411, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.newObject_label.setFont(font)
        self.newObject_label.setText("")
        self.newObject_label.setObjectName("newObject_label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.drawButton.setText(_translate("Dialog", "Wizualizacja"))
        self.addButton.setText(_translate("Dialog", "Klasyfikuj nowy obiekt"))
        self.label_2.setText(_translate("Dialog", "Dane nowego elementu - wprować dane nowego elementu, wartość kolejych atrybutów oddzielone spacją"))
        self.label.setText(_translate("Dialog", "Nowy obiekt to:"))

